/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import MODELO.MODELO_CATEGORIA;
import javax.swing.JOptionPane;

/**
 *
 * @author PERSONAL
 */
public class MODELO_VISTA extends javax.swing.JFrame {

    /**
     * Creates new form MODELO_VISTA
     */
    public MODELO_VISTA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelCustom3 = new org.edisoncor.gui.label.LabelCustom();
        labelCustom1 = new org.edisoncor.gui.label.LabelCustom();
        labelCustom4 = new org.edisoncor.gui.label.LabelCustom();
        labelCustom5 = new org.edisoncor.gui.label.LabelCustom();
        edad = new org.edisoncor.gui.textField.TextFieldRectImage();
        nombre = new org.edisoncor.gui.textField.TextFieldRectImage();
        labelCustom6 = new org.edisoncor.gui.label.LabelCustom();
        l3 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonAeroLeft2 = new org.edisoncor.gui.button.ButtonAeroLeft();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        labelCustom3.setBackground(new java.awt.Color(51, 204, 255));
        labelCustom3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 0), 2, true));
        labelCustom3.setText("NOMBRE");
        jPanel2.add(labelCustom3);
        labelCustom3.setBounds(10, 180, 100, 21);

        labelCustom1.setBackground(new java.awt.Color(51, 204, 255));
        labelCustom1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 0), 2, true));
        labelCustom1.setText("CATEGORIA");
        jPanel2.add(labelCustom1);
        labelCustom1.setBounds(10, 320, 100, 17);

        labelCustom4.setBackground(new java.awt.Color(51, 204, 255));
        labelCustom4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 0), 2, true));
        labelCustom4.setText("EDAD");
        jPanel2.add(labelCustom4);
        labelCustom4.setBounds(220, 80, 63, 17);

        labelCustom5.setBackground(new java.awt.Color(51, 204, 255));
        labelCustom5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 0), 2, true));
        labelCustom5.setText("NOMBRE");
        jPanel2.add(labelCustom5);
        labelCustom5.setBounds(20, 70, 67, 21);

        edad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edadKeyTyped(evt);
            }
        });
        jPanel2.add(edad);
        edad.setBounds(220, 110, 140, 20);

        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });
        jPanel2.add(nombre);
        nombre.setBounds(10, 110, 140, 20);

        labelCustom6.setBackground(new java.awt.Color(51, 204, 255));
        labelCustom6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 0), 2, true));
        labelCustom6.setText("EDAD");
        jPanel2.add(labelCustom6);
        labelCustom6.setBounds(10, 250, 100, 17);

        l3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.add(l3);
        l3.setBounds(10, 350, 110, 20);

        l1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.add(l1);
        l1.setBounds(10, 220, 100, 20);

        l2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.add(l2);
        l2.setBounds(10, 290, 100, 20);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(360, 330, 0, 0);

        buttonAeroLeft2.setBackground(new java.awt.Color(0, 153, 102));
        buttonAeroLeft2.setForeground(new java.awt.Color(153, 153, 0));
        buttonAeroLeft2.setText("CALCULAR");
        buttonAeroLeft2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAeroLeft2ActionPerformed(evt);
            }
        });
        jPanel2.add(buttonAeroLeft2);
        buttonAeroLeft2.setBounds(120, 150, 106, 25);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 380, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        // TODO add your handling code here:
        if ((evt.getKeyChar() < 'a' || evt.getKeyChar() > 'z') && (evt.getKeyChar() < 'A' || evt.getKeyChar() > 'Z')) { //solo permite ingresar letras
            evt.consume();
        }
    }//GEN-LAST:event_nombreKeyTyped

    private void edadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edadKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {//evt.getkeychart()toma el valor que se ingreso en el textfile
     
            evt.consume();
        }
    }//GEN-LAST:event_edadKeyTyped

    private void buttonAeroLeft2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAeroLeft2ActionPerformed
        // TODO add your handling code here:
        if (nombre.getText().equals("") || edad.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "NO SE PUEDE CONTINUAR\nEXISTE ALGUN CAMPO VACIO");
        } else {
            MODELO_CATEGORIA ob1= new MODELO_CATEGORIA(null, Double.parseDouble(edad.getText()));
            l1.setText(nombre.getText());
            l2.setText(edad.getText());
            //            AQUI NO SE COMO CONEVTIR EL METODO, DEL MODELO_CATEGORIA
            
            l3.setText(ob1.categoria(ob1.categoria()));
            
            

    }//GEN-LAST:event_buttonAeroLeft2ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MODELO_VISTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MODELO_VISTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MODELO_VISTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MODELO_VISTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MODELO_VISTA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAeroLeft buttonAeroLeft2;
    private org.edisoncor.gui.textField.TextFieldRectImage edad;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private org.edisoncor.gui.label.LabelCustom labelCustom1;
    private org.edisoncor.gui.label.LabelCustom labelCustom3;
    private org.edisoncor.gui.label.LabelCustom labelCustom4;
    private org.edisoncor.gui.label.LabelCustom labelCustom5;
    private org.edisoncor.gui.label.LabelCustom labelCustom6;
    private org.edisoncor.gui.textField.TextFieldRectImage nombre;
    // End of variables declaration//GEN-END:variables
}
